apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-cluster-admin
subjects:
- kind: User
  name: umesh@thecloudside.com
- kind: User
  name: anthos-cluster-connect@dmart-anthos-project.iam.gserviceaccount.com
- kind: User
  name: 1075787455276@cloudbuild.gserviceaccount.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
